# Generated by Django 3.1 on 2020-08-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sócio',
            name='nome_completo',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
