# Generated by Django 3.1 on 2020-09-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sócio_nome_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sócio',
            name='matrícula',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sócio',
            name='turma',
            field=models.IntegerField(default=28),
            preserve_default=False,
        ),
    ]
