# Generated by Django 3.1 on 2020-09-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200901_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sócio',
            name='matrícula',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='sócio',
            name='turma',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
