# Generated by Django 3.1 on 2020-09-02 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200901_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluxo', models.CharField(choices=[('E', 'ENTRADA'), ('S', 'SAÍDA'), ('R', 'REALOCAÇÃO')], max_length=1)),
                ('finalidade', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('observações', models.TextField()),
                ('responsável', models.CharField(max_length=25)),
                ('data_da_movimentação', models.DateField(default=datetime.datetime(2020, 9, 2, 17, 55, 46, 476185, tzinfo=utc))),
            ],
        ),
    ]
