# Generated by Django 3.1 on 2020-09-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_financeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='data_da_movimentação',
            field=models.DateField(auto_now_add=True),
        ),
    ]
