# Generated by Django 3.1 on 2020-09-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200902_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='sócio',
            name='celular',
            field=models.CharField(default='(99) 99999-9999', max_length=16),
            preserve_default=False,
        ),
    ]
