# Generated by Django 3.1 on 2020-09-06 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sócio_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociaçãoCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duração', models.CharField(choices=[('S', 'SEMESTRAL'), ('A', 'ANUAL')], max_length=1)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='sócio',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sócio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='socios'),
        ),
        migrations.AlterField(
            model_name='sócio',
            name='matrícula',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sócio',
            name='turma',
            field=models.CharField(max_length=2),
        ),
        migrations.CreateModel(
            name='Associação',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.associaçãocategoria')),
                ('sócio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.sócio')),
            ],
        ),
    ]
