# Generated by Django 3.1 on 2020-09-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200906_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='sócio',
            name='email',
            field=models.EmailField(default='example@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
