# Generated by Django 3.1 on 2020-09-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sócio_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='associaçãocategoria',
            name='reassociação',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
