# Generated by Django 3.1 on 2020-09-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200907_0750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Associação',
            new_name='Associacao',
        ),
        migrations.RenameModel(
            old_name='AssociaçãoCategoria',
            new_name='AssociacaoCategoria',
        ),
        migrations.AlterModelOptions(
            name='associacao',
            options={'verbose_name': 'Associação', 'verbose_name_plural': 'Associações'},
        ),
        migrations.AlterModelOptions(
            name='associacaocategoria',
            options={'verbose_name': 'Associação Categoria', 'verbose_name_plural': 'Associação Categorias'},
        ),
    ]
