# Generated by Django 3.1 on 2020-09-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200907_0800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Associacao',
            new_name='Associação',
        ),
        migrations.RenameModel(
            old_name='AssociacaoCategoria',
            new_name='AssociaçãoCategoria',
        ),
        migrations.AlterModelOptions(
            name='associação',
            options={'verbose_name_plural': 'Associações'},
        ),
    ]
