# Generated by Django 3.1 on 2020-09-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200907_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='associação',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to='associação/comprovantes'),
        ),
        migrations.AddField(
            model_name='associação',
            name='conta_destino',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
