# Generated by Django 3.1 on 2020-09-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200908_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associação',
            name='conta_destino',
            field=models.CharField(blank=True, choices=[('BB', 'BANCO DO BRASIL'), ('CX', 'CAIXA ECONÔMICA'), ('ST', 'SANTANDER')], max_length=2, null=True),
        ),
    ]
