# Generated by Django 3.1 on 2020-09-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200910_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associaçãocategoria',
            old_name='valor',
            new_name='primeira',
        ),
    ]
