# Generated by Django 3.1 on 2020-08-31 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20200829_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produtos'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='T', max_length=5)),
                ('amount', models.FloatField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
            ],
        ),
    ]
