# Generated by Django 3.1 on 2020-08-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20200830_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes'),
        ),
    ]
