# Generated by Django 3.1 on 2020-08-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_order_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='AG', max_length=5),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='size',
            field=models.CharField(choices=[('PPBL', 'PPBL'), ('PBL', 'PBL'), ('MBL', 'MBL'), ('GBL', 'GBL'), ('GGBL', 'GGBL'), ('XGBL', 'XGBL'), ('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('EXGG', 'EXGG')], max_length=4),
        ),
    ]
