# Generated by Django 3.1 on 2020-09-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_order_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AG', 'AGUARDANDO'), ('PR', 'PROCESSANDO'), ('CC', 'CONCLUIDO'), ('XX', 'CANCELADO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('TR', 'Transferência'), ('ST', 'Stripe')], max_length=2),
        ),
    ]
