# Generated by Django 3.1 on 2020-09-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20200901_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gateway',
            field=models.CharField(choices=[('O', 'ONLINE'), ('P', 'PRESENCIAL')], default='O', max_length=1),
            preserve_default=False,
        ),
    ]
