# Generated by Django 3.1 on 2020-09-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='final_price',
            field=models.FloatField(null=True),
        ),
    ]
